service: payment-lambda

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-layers

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: live
  environment:
    test:
      TEST_STRIPE_SECRET_KEY: ${env:TEST_STRIPE_SECRET_KEY}
    live:
      LIVE_STRIPE_SECRET_KEY: ${env:LIVE_STRIPE_SECRET_KEY}

functions:
  checkout:
    handler: checkout.handler
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - http:
          path: checkout
          method: POST
          cors: true
