# https://stylelint.io

plugins:
  - stylelint-scss
  # - stylelint-a11y

syntax:
  - scss

customSyntax: postcss-scss

extends:
  # standard > recommended
  - stylelint-config-standard
  # Order by properties
  - stylelint-config-recess-order

rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  color-function-notation: modern
  no-empty-source: null
  selector-id-pattern: null
  selector-class-pattern: null
