name: Deploy to S3

on:
  push:
    branches:
      - main
  #  pull_request:
  #    branches:
  #      - main

jobs:
  deploy:
    name: deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: nrwl/nx-set-shas@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Dependencies
        run: yarn

      - name: Company Transpile
        run: |
          npx nx run company-app:build
          npx nx run company-app:export
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Profile Transpile
        run: |
          npx nx run profile-app:build
          npx nx run profile-app:export
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_LIVE_LAMBDA_ENDPOINT: ${{ secrets.NEXT_LIVE_LAMBDA_ENDPOINT }}
          NEXT_LIVE_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_LIVE_STRIPE_PUBLIC_KEY }}
          NEXT_TEST_LAMBDA_ENDPOINT: ${{ secrets.NEXT_TEST_LAMBDA_ENDPOINT }}
          NEXT_TEST_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_TEST_STRIPE_PUBLIC_KEY }}
          NEXT_LHCI_GITHUB_APP_TOKEN: ${{ secrets.NEXT_LHCI_GITHUB_APP_TOKEN }}

      - name: Deploy Company to S3
        run: bash scripts/sub_company_directory.sh

      - name: Deploy Profile to S3
        run: bash scripts/sub_profile_directory.sh
